### ISSUE TITLE
Testing Mybinder

### ISSUE THREAD

**Issue by negin513** [UCAR-SEA/SEA-ISS-Template#3]

**Comment by kafitzgerald** [comment]
Just tested this quickly and it looks like it works (w/ info manually entered on mybinder.org). Obviously you can't run the notebook that uses matplotlib and numpy right now because those aren't in the environment, but basic Python commands work.  

I'll go ahead and add in a badge to the template and some guidance for submitters. 

I'm inclined to keep the template environment simple and create another example submission that's more interactive with additional dependencies if that's desired.  Let me know if you had something else in mind @negin513.
